---
apiVersion: v1
kind: Namespace
metadata:
  name: challenge-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: challenge-stg
---
apiVersion: v1
kind: Namespace
metadata:
  name: challenge-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: challenge-dev
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-container
          image: rocajp/hello-world:1.0.0
          ports:
            - containerPort: 80
---
