name: Container image build
on:
  push:
    branches:
      - main
env:
  DOCKER_REGISTRY: 'docker.io'
  # Should be a GH Secret (only for challenge)
  DOCKER_USERNAME: 'rocajp'
  # Should be a GH Secret (only for challenge)
  DOCKER_PASSWORD: 'dckr_pat_4WYx03tGT_dWgI_gcY2jnNa7EUU'
  IMAGE_NAME: 'rocajp/hello-world'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Docker Hub registry
      run: echo ${DOCKER_PASSWORD} | docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} --password-stdin
    
    - uses: cperezabo/setup-git-mkver@v1.2.0
      with:
        version: "latest"
    
    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(git mkver next)

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$(git mkver next)

    - name: Update Semantic Version
      run: |
        git config --global user.email "rocajp@gmail.com"
        git config --global user.name "Juan Pablo Roca"
        git mkver tag
        git push --follow-tags

    - name: Clean up for self-hosted runner in VM
      run: |
        docker image rm $IMAGE_NAME:latest
        docker image rm $IMAGE_NAME:$(git mkver next)
