name: Deploy Container
on:
  push:
    branches:
      - main
env:
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_USERNAME: 'rocajp'
  DOCKER_PASSWORD: 'dckr_pat_4WYx03tGT_dWgI_gcY2jnNa7EUU'
  IMAGE_NAME: 'hello-world'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Docker Hub registry
      run: echo ${DOCKER_PASSWORD} | docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} --password-stdin
        
    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:$(git describe --tags --abbrev=0)

    - name: Push Docker image
      run: |
        docker push ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:$(git describe --tags --abbrev=0)

    - name: Update Semantic Version
      run: |
        git tag -a $(git describe --tags --abbrev=0) -m "Version $(git describe --tags --abbrev=0)"
        git push --follow-tags

    #- name: Deploy to Kubernetes (if needed)
      # Add your Kubernetes deployment steps here
      # You can use kubectl to apply your updated manifests

    - name: Clean up for self-hosted runner in VM
      run: |
        docker image rm ${IMAGE_NAME}:latest
        docker image rm ${IMAGE_NAME}:$(git describe --tags --abbrev=0)
